feat: Implement CLIENT PAUSE & UNPAUSE
denodrivers/redis pull request #181
Opened 2021-02-05 13:07 UTC by siyopao

Part of #174.

Hello :wave: My first contribution! Please let me know if it can be improved. Thanks!

2021-02-05 13:13 UTC, siyopao commented
Oh, the test fails. I think PAUSE with the mode parameter only works on Redis >= 6.2.0 Also UNPAUSE. So I could remove the mode and UNPAUSE or... any suggestions?

2021-02-06 08:02 UTC, uki00a requested changes
@siyopao Thank you for the contribution! 

> Oh, the test fails. I think PAUSE with the mode parameter only works on Redis >= 6.2.0. Also UNPAUSE. So I could remove the mode and UNPAUSE or... any suggestions?

OK, let's leave those for now. We'll try to support those in a future version. :wink:

2021-02-06 08:02 UTC, uki00a commented on command.ts
> +  client_unpause(): Promise<Status>;
Please remove `client_unpause` method!

2021-02-06 09:48 UTC, siyopao commented on command.ts
> +  client_pause(timeout: number, mode?: "WRITE" | "ALL"): Promise<Status>;
Updated! Thanks.

2021-02-06 09:48 UTC, siyopao commented on command.ts
> +  /**
Fixed! Thanks.

2021-02-06 09:48 UTC, siyopao commented on redis.ts
> +  client_pause(timeout: number, mode?: "WRITE" | "ALL") {
Removed. Thanks!

2021-02-06 09:49 UTC, siyopao commented on command.ts
> +  client_unpause(): Promise<Status>;
Removed for now. Thanks!

2021-02-06 09:54 UTC, uki00a approved these changes
LGTM, thank you for your contribution! :+1:

2021-02-06 09:56 UTC, merged

2021-02-07 23:00 UTC, siyopao commented
Thanks for the great experience! I hope I can contribute more in the future.