feat: Implement CLIENT UNBLOCK
denodrivers/redis pull request #195
Opened 2021-02-24 00:04 UTC by siyopao

Part of #174.

2021-02-24 00:26 UTC, siyopao commented
Hmm, `acl_test` failed. It looks like the CI is now using Redis 6.2 which is affecting some of the existing tests.

2021-02-24 00:33 UTC, siyopao commented
Okay, created https://github.com/denodrivers/redis/pull/196. If that looks good I can rebase on it after.

2021-02-25 14:04 UTC, uki00a requested changes
Looks good! Just a minor nitpick:

2021-02-25 14:04 UTC, uki00a commented on tests/connection_test.ts
> +    await new Promise((r) => setTimeout(r, 100)); // give some leeway for the command to reach redis
Ditto

2021-02-26 00:11 UTC, siyopao commented on tests/connection_test.ts
> +    await new Promise((r) => setTimeout(r, 100)); // give some leeway for the command to reach redis
That is much nicer. Thanks. Fixed!

2021-02-26 00:12 UTC, siyopao commented on tests/connection_test.ts
> +    await new Promise((r) => setTimeout(r, 100)); // give some leeway for the command to reach redis
Thanks. Fixed here as well.

2021-02-26 00:36 UTC, uki00a approved these changes
LGTM, thanks @siyopao! :+1:

2021-02-26 00:37 UTC, merged