feat: Implement CLIENT LIST
denodrivers/redis pull request #205
Opened 2021-03-01 11:55 UTC by siyopao

Part of #174.

2021-03-01 11:56 UTC, siyopao commented on command.ts
> +export type ClientPauseMode = "WRITE" | "ALL";
Sorry, moved this to keep it in alphabetical order.

2021-03-02 14:14 UTC, uki00a requested changes
Looks good! :+1: Just a minor nitpick:

2021-03-02 14:14 UTC, uki00a commented on redis.ts
> +      throw new Error("only one of `type` or `ids` may be specified");
```suggestion
      throw new Error("only one of `type` or `ids` can be specified");
```

2021-03-03 08:17 UTC, siyopao commented on redis.ts
> +      throw new Error("only one of `type` or `ids` may be specified");
Updated! Thanks!

2021-03-03 14:23 UTC, uki00a approved these changes
LGTM, thanks @siyopao! :+1:

2021-03-03 14:23 UTC, merged