added username+password auth support
denodrivers/redis pull request #310
Opened 2022-06-03 10:14 UTC by scott-ling

Fixes issue #300

You can now use redis client with cloud hosted redis (redis enterprise/cloud stack) or any other redis server that has user+password authentication.

PR is not breaking, but has changed RedisConnectionOptions to support an optional username: string property.

Tests not included since, only tests that make sense require a redis instances setting up with:
- password only (auth token only)
- username + password
- no auth

I did not see mock redis server for this in tests, and existing test for authentication is only checking if a parameter has been passed and is valid.  Which exception handling catches anyway.

ps. been a while since I did a PR.  (also note, I have this code in production, be nice to use official repo for this. )

2022-06-03 13:33 UTC, uki00a requested changes
@scott-ling Thanks for working on this!

I just left one comment, other than that it looks good overall! :+1:

2022-06-03 13:37 UTC, scott-ling commented
there ya go, sorry about that

2022-06-03 13:38 UTC, uki00a approved these changes
LGTM, thanks for the contribution! :+1:

I'll release a new version in the coming days

2022-06-03 13:38 UTC, merged

2022-06-03 13:44 UTC, scott-ling commented
tx, look forward to it.

On Jun 3 2022, at 2:38 pm, Yuki Tanaka ***@***.***> wrote:
>
>
> @uki00a approved this pull request.
> LGTM, thanks for the contribution! 👍
> I'll release a new version in the coming days
> —
> Reply to this email directly, view it on GitHub (https://github.com/denodrivers/redis/pull/310#pullrequestreview-994927378), or unsubscribe (https://github.com/notifications/unsubscribe-auth/ATXWUNUHO2NH56NHSYTNDNLVNIDF5ANCNFSM5XYBIITA).
> You are receiving this because you were mentioned.
>

2022-06-04 12:26 UTC, uki00a commented
Released in [v0.26.0](https://github.com/denodrivers/redis/releases/tag/v0.26.0)!

2022-06-04 12:27 UTC, scott-ling commented
great to know, will look at other PR and Issues tomorrow, see where else I can help.

On Jun 4 2022, at 1:26 pm, Yuki Tanaka ***@***.***> wrote:
>
>
> Released in v0.26.0 (https://github.com/denodrivers/redis/releases/tag/v0.26.0)!
> —
> Reply to this email directly, view it on GitHub (https://github.com/denodrivers/redis/pull/310#issuecomment-1146599684), or unsubscribe (https://github.com/notifications/unsubscribe-auth/ATXWUNXMGDFKKXZ5HSROGRTVNNDOTANCNFSM5XYBIITA).
> You are receiving this because you were mentioned.
>